Fix pipeline

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -57,11 +57,16 @@ jobs:
       # =====================================
       - name: Wait for SSH
         run: |
-          echo "Waiting for SSH to be available..."
-          until nc -z $PUBLIC_IP 22; do
+          echo "Waiting for SSH..."
+          for i in {1..30}; do
+            if ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 ubuntu@$PUBLIC_IP "echo ok" 2>/dev/null; then
+              echo "SSH is ready!"
+              exit 0
+            fi
             sleep 5
           done
-          echo "SSH is ready!"
+          echo "SSH connection failed."
+          exit 1
 
       # =====================================
       # 5️⃣ Installer Ansible
